### ISSUE TITLE
Recognizing files from the desktop and displaying them in checkboxes

### ISSUE THREAD

**Issue by jashwanth0712** [jashwanth0712/Safekey#4]
Create a page that takes the directory path and displays all the files in that directory as checkboxes 
user selects the files and clicks submit and , the selected files list would be stored in a variable and displayed when clicked submit

**Comment by karthik825** [comment]
Check boxes added and the files selected were also being displayed

**Comment by karthik825** [comment]
Check boxes updated and displayed, issue resolved
